### ISSUE TITLE
remove JGI faa and fna files from data object outputs

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#105]
Based on conversation with @dehays:  
In the schema, we want the data objects that represent the assembly files (i.e., faa and fna files) to come from AIM 2's pipeline (i.e., NMDC).   
Currently, the files come from JGI. So, need to remove the JGI faa and fna data objects from data. We only want to keep the JGI fastq files.

cc @cmungall

**Comment by cmungall** [comment]
This makes sense. It was useful having them there as exemplars/placeholders, but time to get rid of them.

**Comment by wdduncan** [comment]
Done. See PR https://github.com/microbiomedata/nmdc-metadata/pull/106
