### ISSUE TITLE
Generate markdown docs from nmdc schema

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#11]
@deepakunni3 can help with this

**Comment by wdduncan** [comment]
@deepakunni3 told me not load the *.md files on the github site. I can recall the reason why. The *.md files are being used to generate documentation on https://microbiomedata.github.io/nmdc-metadata/.

**Comment by deepakunni3** [comment]
@wdduncan The MD files generated for the documentation may have formatting and other things that are specific to GitHub pages. And these formatting can be rendered incorrectly in traditional markdown.

But is there a use-case for having the markdown files all by itself, in addition to the documentation site:  https://microbiomedata.github.io/nmdc-metadata/

IIRC, in this ticket @cmungall was referring to setting up a documentation site. Which we have done. So perhaps we can close this ticket (unless I missed something here)

**Comment by wdduncan** [comment]
@cmungall I think we can close this ticket. Agree?
