### ISSUE TITLE
integrating PROV into schema

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#113]
How are planning to integrate PROV with the NMDC schema?   
Currently, we have a place to put PROV activities in the `activity set` slot. But, other questions follow:  
1. Should biosample processing (and omics processing) be a subtype of PROV activity?
2. Do we want PROV `wasGeneratedBy` to act as inverse relation to `has_output`?
3. Do you want to relate NMDC data processings (workflows?) to GOLD projects using `wasInformedBy` (https://www.w3.org/TR/prov-o/#wasInformedBy)? I think `wasGeneratedBy` could be more appropriate.  

cc @cmungall @dehays

**Comment by cmungall** [comment]
PROV is a nice structure but we should not be too hamstrung by it at this stage. I am confident if we come up with the right structure it will align well to PROV.

**Comment by wdduncan** [comment]
@cmungall I think this we've tackled this one with Aim 2 workflows (e.g., assembly file `was generated by` metagenome assembly (workflow execution activity).

Let me know if you want to re-open.
