### ISSUE TITLE
Priorities before Friday July, 17

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#114]
@dehays @cmungall @scanon @hubin-keio 

If I recall, Kitware needs the dataset settled by Friday 7/17. Can we prioritize what workflows we might be able to get to them? E.g.:  
- readQC
- nucleotide assembly
- genome annotation
- none of the above?

**Comment by dehays** [comment]
The work thus far from @scanon and @chienchi has been the following three. I suggest addressing them in this order.

1) readQC (in one example it is marked as "SampleQC" but that is a misnomer.  This takes in raw reads and produces filtered reads and some statistics.)

2) metagenome assembly

3) metagenome annotation

**Comment by wdduncan** [comment]
We're settled on this ... so closing.
