### ISSUE TITLE
iterate on gold->json converter

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#12]
TBD: use the generated python classes vs direct creation of json

At first we will select the most used fields in GOLD and prioritize these for mapping to mixs

**Comment by cmungall** [comment]
For now the output is here https://github.com/microbiomedata/GOLD-ontology-translation/tree/master/notebooks/output can we put in this repo @wdduncan ?

**Comment by wdduncan** [comment]
Added study and project to the schema, and moved external repos into nmdc-metadata repo.

**Comment by wdduncan** [comment]
We are using the NMDC python classes to generate JSON. Schema, now has study, project, biosample, and data object classes. 

Needs:
* PI table
* Links to data objects (e.g., EMSL data)
