### ISSUE TITLE
remove isolate genomes

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#125]
cc @dehays

**Comment by dehays** [comment]
This will involve the removal of 40 biosamples and 40 omics_processing objects.  If I give you a set of IDs can you you remove them.  Or how best to ensure that they stay removed with you your ETL starting with the GOLD DB exports for FICUS?

**Comment by wdduncan** [comment]
Yes. I can remove the records from the GOLD biosample and project tables. The solution will be hacky ... Hopefully the next GOLD export excludes them :)
