### ISSUE TITLE
Generate a UML diagram for whole schema

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#17]
See https://github.com/biolink/biolinkml/blob/master/notebooks/examples.ipynb for an example

**Comment by wdduncan** [comment]
I think we may be able to close this. We are using the Makefile to generate the full schema.
The call to build the schema in python is:
```
python schema/generate_uml.py schema/nmdc.yaml schema/nmdc_schema_uml.png
```

**Comment by deepakunni3** [comment]
This is done and we have a target in the Makefile too.
