### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by hubin-keio** [microbiomedata/nmdc-metadata#198]
I tried a several links in the documentation and they all seemed broken. For example the following one from https://github.com/microbiomedata/nmdc-metadata/issues/184:
https://microbiomedata.github.io/nmdc-metadata/docs/GeneProduct

And this one from README.md:
https://microbiomedata.github.io/nmdc-metadata

**Comment by wdduncan** [comment]
Working on this. See #203 for details.

**Comment by cmungall** [comment]
fixed
