### ISSUE TITLE
merge Brodie biosamples and set references from omics_processing objects

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#210]
Currently - nmdc-metadata/blob/master/metadata-translation/src/data/nmdc_database.json.zip contains biosamples representing both RNA and DNA samples.  Sequencing omics_processing objects refer to these biosample objects.

For Brodie - we need to update the biosample objects to merge the GOLD RNA and DNA biosample objects into single objects.  The new object will use the IGSN id provided.

https://docs.google.com/spreadsheets/d/19PH8F-YqTZ3oUoWg1vKtPKHZT9YznXoA

The omics_processing entities that previously referred to the pre merge biosample objects would need to be updated to refer to the new post merge object, i.e. the one with the igsn: ID

Also - the spreadsheet above contains EMSL dataset IDs in column H that correspond to omics_processing entitiies (The omics_processing objects use the EMSL dataset ID as ID.). These need to reference the new biosamples.

That is, all metaG, metaT and EMSL (In this case NOM) omics_processing entities need to reference the new IGSN ID'd samples according to the spreadsheet above

**Comment by dwinston** [comment]
for omics_processing entities, only to-IGSN has_input IDs

**Comment by dwinston** [comment]
done via #224
