### ISSUE TITLE
Natural Organic Matter / Organic Matter Characterization Analysis WF Activity and output JSON

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#214]
Very similar to the metabolomics work that @corilo already did

**Comment by dehays** [comment]
I believe this also needs a workflow execution activity added to the NMDC Schema

**Comment by wdduncan** [comment]
The schema now has a `nom analysis activity set`. Can we close this ticket?

**Comment by dehays** [comment]
yes
