### ISSUE TITLE
Read-based Taxonomy Analysis Activity and DataObject for output files JSON

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#215]
First we need a ReadBased Analysis Activity in the NMDC Schema (class and appropriate slots) to nmdc.yaml, and Second check that the following are valid and adequate

https://portal.nersc.gov/cfs/m3408/meta/ReadbasedAnalysis_activity.json
https://portal.nersc.gov/cfs/m3408/meta/ReadbasedAnalysis_activity_data_objects.json

**Comment by wdduncan** [comment]
We may need to add an empty `ReadbasedAnalysis` analysis class. All the fields are the parent class.
