### ISSUE TITLE
support MetabolomicsAnalysisActivity properties in activity_set or a variant

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-metadata#227]
In the json schema, [activity_set](https://github.com/microbiomedata/nmdc-metadata/blob/6e0c5d1a2534eca59226b0a491cb25ee33d6676b/schema/nmdc.schema.json#L2018) is a list of references to `WorkflowExecutionActivity` objects. However, when a conceptual subclass such as `MetabolomicsAnalysisActivity` is checked for conformance, it is considered invalid by `jsonschema` if for example it has a [has_metabolite_quantifications](https://github.com/microbiomedata/nmdc-metadata/blob/6e0c5d1a2534eca59226b0a491cb25ee33d6676b/schema/nmdc.schema.json#L1002) field because `WorkflowExecutionActivity` specifies that `"additionalProperties": false`. Thus, `WorkflowExecutionActivity` should include a union of the properties of its subclasses.

This is an issue with conformance for the data of @corilo 

@wdduncan @cmungall what do you think?

**Comment by wdduncan** [comment]
@dwinston Do you have link to file I should look at to test with?

**Comment by dwinston** [comment]
Sure, https://nmdcdemo.emsl.pnnl.gov/metabolomics/metadata/Froze_Core_2015_S2_0_10_7_Metab.json

**Comment by dwinston** [comment]
'has_calibration' therein is not currently part of the schema but should be there as a string-typed id reference. @corilo array-typed, i.e. can the calibration be relative to multiple entities?

**Comment by dwinston** [comment]
@wdduncan changing the subject of this issue to accommodate a solution where another database "set" is introduced, e.g. MAGsAnalysisActivity has mags_activity_set

**Comment by corilo** [comment]
No, it's always only relative to one entity

Em sex., 22 de jan. de 2021 às 12:56, Donny Winston <
notifications@github.com> escreveu:

**Comment by wdduncan** [comment]
see also #230

**Comment by wdduncan** [comment]
@dwinston I'm going to close this b/c our creation of different activity sets addresses this. Please re-open if you think this is still an issue.

**Comment by dwinston** [comment]
I think it's still an issue until e.g. #231 is merged. I won't re-open because I expect #231 to merge soon.
