### ISSUE TITLE
Vulnerabilities in one of the dependencies in this repo

### ISSUE THREAD

**Issue by deepakunni3** [microbiomedata/nmdc-metadata#26]
GitHub report: https://github.com/microbiomedata/nmdc-metadata/network/alert/GOLD-ontology-translation/notebooks/requirements.txt/pycrypto/open

Not sure if this is of concern, but would be good to see if we can avoid depending on the vulnerable packages altogether.

**Comment by wdduncan** [comment]
Yes. I remember seeing that. I'm not seeing a security warning now though.

**Comment by wdduncan** [comment]
Since we can't access the vulnerably page anymore, I am going to close this.

**Comment by cmungall** [comment]
still there

**Comment by cmungall** [comment]
we also need to reduce our requirements.txt to only actual requirements

**Comment by cmungall** [comment]
See also #50

**Comment by wdduncan** [comment]
The vulnerability has been addressed.

**Comment by cmungall** [comment]
Fixed by #51
