### ISSUE TITLE
Incorrect heading - NCBI taxonomy name used when entries are habitats not taxonomy

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-metadata#263]
![image (1)](https://user-images.githubusercontent.com/1504015/107835048-004eb680-6d4d-11eb-8820-b12abd793eac.png)

Feedback: 
not the right database for taxonomy. these are habitat names not species names

@subdavis adding you as this might be a UI issue - not sure where "NCBI taxonomy name" is coming from

**Comment by pvangay** [comment]
@kfagnan actually... NCBI's taxonomy includes a bunch of XYZ metagenomes! Going to close this issue for now. https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=408169
