### ISSUE TITLE
Ignore GOLD biosamples for which the ACTIVE field is false

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#27]
The project and biosample JSON produced includes several hundred more biosamples than projects with many of the biosamples referring to projects not represented in the JSON.   I believe this is due to the inclusion of biosample records from GOLD that are not ACTIVE.

**Comment by deepakunni3** [comment]
I believe this is now being done as part of https://github.com/microbiomedata/nmdc-metadata/blob/master/GOLD-ontology-translation/notebooks/translate-study-project-biosample.ipynb notebook. 

@wdduncan Thoughts?

**Comment by wdduncan** [comment]
Projects are being filtered for only records where "active = 'Yes'"
```
q = """
select 
    *
from
    project
where
    active = 'Yes'
"""
project = sqldf(q)
```
Same for studies and biosamples.
