### ISSUE TITLE
GSP - Inconsistent location information 

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#282]
Search results show Ohio and Ohio, USA separately.  See attached screenshot.  

Conferred with @dehays and he said that the "Ohio" strings are coming from GOLD biosample records geographic_location field.  These happen to all be for Kelly Wrighton. 
<img width="656" alt="ohio" src="https://user-images.githubusercontent.com/79225425/108574423-3d2a2880-72cc-11eb-9920-d2130c7522fd.png">

**Comment by TBKReddy** [comment]
All instances of Ohio and Ohio, USA have been now updated to USA: Ohio at the source in GOLD.  The same can be done in the NMDC.  The correct format we use for geographic location is USA: City, State. 

@jagadishcs check for other inconsistencies in the geographic location field. Get those fixed and communicate the update values  for NMDC JSON update.

**Comment by dehays** [comment]
Believe this has now been addressed in GOLD so should be reflected once GOLD data is ETLed and loaded into search application.

**Comment by jagadishcs** [comment]
Yes, this was updated already.
