### ISSUE TITLE
reorganize existing repo and arrange using standard layout

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#288]
You can use https://github.com/cmungall/ontology_associations as a template

 * requirements.txt etc
 * tests/
     *  data/
 * nmdc_metadata/
      * datamodel.  ## autogenerated from schema below here
            * nmdc.py
            * core.py
            * associations.py
            * prov.py
 * src
     * schema/. ## hand edited
        * nmdc.yaml
        * ....ymp
  * jsonschema  ## autogenerated
       * nmdc.schema.json
   * shex etc

And setup github actions to deploy nmdc_metadata to pypi (we have many examples of how to do this..). Note this simultaneously versions the schema and the python keeping both in sync

Once this is done, we can move ETL out to separate repo, the ETL repo will use the py modules

**Comment by wdduncan** [comment]
Update:  
Create new repo to hold the nmdc schema: https://github.com/microbiomedata/nmdc-schema

cc @cmungall @dwinston @dehays @kfagnan @jbeezley @ssarrafan

**Comment by wdduncan** [comment]
Update:  You can now install the nmdc-schema using pip: `pip install nmdc-schema`.  

There is still a lot of documentation work to do.

**Comment by wdduncan** [comment]
Outcomes from conversation with @dwinston:

1. rename the repo `nmdc-metadata-pipelines`; used for orchestrating different pipelines such as GOLD
2. tag versions with releases

structure:
nmdc-pipelines
  - target (used for outputs of pipelines) or should this be in data output
  - resources (used for inputs into pipelines; e.g. GOLD database dump)
       - data source
       - data sync
       - data output

more to come ...

**Comment by wdduncan** [comment]
Please move this to May sprint.
@dwinston and I are getting close to finishing this. Probably a `medium` sized issue.

**Comment by wdduncan** [comment]
Update

I have removed number of directories. See PR https://github.com/microbiomedata/nmdc-metadata/pull/344 for details (or view repo on branch `issue-288`).

Awaiting feedback before merging.

**Comment by wdduncan** [comment]
A number of directories have been deleted. See PR https://github.com/microbiomedata/nmdc-metadata/pull/344

The schema has been moved to [nmdc-schema](https://github.com/microbiomedata/nmdc-schema).  
The ETL now lives in [nmdc-runtime](https://github.com/microbiomedata/nmdc-runtime).  
The custom notebooks that were created in the early stages of `NMDC` have been archived to [archived-metadata-notebooks](https://github.com/microbiomedata/archived-metadata-notebooks). This notebooks include:
- [GOLD-level-analysis](https://github.com/microbiomedata/archived-metadata-notebooks/tree/main/GOLD-level-analysis)
- [GOLD-path-translation](https://github.com/microbiomedata/archived-metadata-notebooks/tree/main/GOLD-path-translation)
- [MIxS-ontology-translation](https://github.com/microbiomedata/archived-metadata-notebooks/tree/main/MIxS-ontology-translation)
