### ISSUE TITLE
revert simplification of sample slot values

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#291]
The changes here were made due to the need for a qucik turnaround for GSP:

https://github.com/microbiomedata/nmdc-metadata/commit/aec1e2b302305871b563504ffec9c17d6638500d

but we should revert the overrides of mixs ranges now. This is not a scalable solution long term, as many of these need to be modeled as complex objects not literals/strings. This is causing confusion: #290

**Comment by wdduncan** [comment]
Schema changes done. See PRs: https://github.com/microbiomedata/nmdc-metadata/pull/298 and https://github.com/microbiomedata/nmdc-metadata/pull/297.

Closing for now.
