### ISSUE TITLE
consistent format for EnvO references in biosample objects

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#294]
Currently - biosamples provided for use in the portal have two different forms ENVO_00000446 and ENVO:00000446

Pajau noticed that none of the Brodie or Wrighton (and as it turns out, many of the Stegen) biosamples participate in EnvO search filtering.  I checked and saw that we did seem to be including values for the MIxS/EnvO triad for all the biosamples.  Jon pointed out this morning that the format using the '_' was unexpected and that those values did not return values when looking up the string values from EnvO.

Can we decide on which format is correct?  (I believe it is ENVO:00000446 ) and then consistently produce JSON that uses the correct format?

**Comment by wdduncan** [comment]
` ENVO:00000446` is correct. I thought I was converting `ENVO_` to `ENV:` in ETL. But, I must have missed that. I'll need to fix.

**Comment by wdduncan** [comment]
@dehays I've resolved this. env_broad/local/medium values now have an ":" instead of "_". E.g., "ENVO:1234".

See https://github.com/microbiomedata/nmdc-metadata/pull/295

cc @dwinston @jbeezley
