### ISSUE TITLE
Figure out interaction between smartsheets and GitHub

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#30]
We use GitHub for fine-grained issues. I have added a [high priority](https://github.com/microbiomedata/nmdc-metadata/labels/high%20priority) label to this tracker so that I can communicate leadership priorities. Currently these are mostly things we need for GSP.

I had also considered making a GH project for tracking GSP items (this could be used for both pilot and this repo) but this would create confusion as to what goes in smartsheets vs GH, cc @dehays 

There are ways to hook these systems together: https://www.google.com/search?q=smartsheet+github+integration but not sure if it's worth exploring

**Comment by dehays** [comment]
@cmungall Yes, there are ways to set event triggers and use their APIs to connect Smartsheet and GitHub.  Before someone spends time on that - you could just add the link to an issue here for anything you add to a Smartsheet.  

Two things I think I understand 1) Aim 1 is happy managing work at the GitHub level (Are EMSL A1 people using this repo?) . 2) While providing the 'what's the plan' Smartsheet interface to Emiley and other leadership minimizing the time burden in maintaining that it hugely important (if it's too expensive in time it just won't happen).
Toward the interaction between Smartsheet and GitHub - I think even the issues labeled as high priority, while they are high priority, are at a finer-grained resolution than what Emiley is interested in.

**Comment by dehays** [comment]
Closing this after last weeks discussion - 

Group issues by Milestones with expected completion dates - Shweta will use these to update A1 Smartsheet

Enriched Curation work in issues for this repo

EMSL work (sample mapping, experiment metadata) can be managed directly in Smartsheet

Emiley / Jagadish FICUS curation can be managed directly in Smartsheet

Jagadish work with Bill on GOLD - MixS mapping managed in GitHub issues
