### ISSUE TITLE
For discussion:  nitro and tot_nitro_content for schema

### ISSUE THREAD

**Issue by StantonMartin** [microbiomedata/nmdc-metadata#321]
The initial Bioscales FAIR data mapping included the parameter nitro as it's MixS term.  This would not validate against the schema because it is not included. Subsequently the Bio Scales team noted the
tot_nitro_content parameter in the schema and changed its mapping.  So there is no  current issue.  Question for NMDC, should the schema include the term nitro as well as tot_nitro_content since they are both in MixS?  They are defined almost synonymously, but the tot_nitro_content term allows for more units:
 
tot_nitro_content  units: microgram per liter, micromole per liter, milligram per liter

nitro  units:  micromole per liter

**Comment by wdduncan** [comment]
Can you please file ticket on the MIxS tracker: https://github.com/GenomicsStandardsConsortium/mixs/issues

**Comment by StantonMartin** [comment]
Done.

https://github.com/GenomicsStandardsConsortium/mixs/issues/122

Closing
