### ISSUE TITLE
Mapping/subsetting of EnvO terms specific to MIxS environmental packages

### ISSUE THREAD

**Issue by jagadishcs** [microbiomedata/nmdc-metadata#325]
@elishawc @dehays @ssarrafan @TBKReddy

Mapping of EnvO terms with specific MIxS environmental packages, so that subset of EnvO terms can be used as CV terms for NMDC by MIxS environmental packages.

**Comment by ssarrafan** [comment]
Hi @jagadishcs, 
I've added this issue to the April sprint and Sprint 1 milestone.

**Comment by ssarrafan** [comment]
@jagadishcs is there any update on this issue?  Can it be moved to "in progress"?

**Comment by dehays** [comment]
This is in progress.  This week's A1 meeting slot was used to plan for addressing subsetting EnvO terms by MIxS package and next week's 4/28 meeting is dedicated to @jagadishcs @cmungall @wdduncan and @elishawc  doing this for the soil package.

**Comment by wdduncan** [comment]
We need to close this issue, and break it up into separate issues for each mixs package.  
Each package will be addressed in the May sprint.
