### ISSUE TITLE
Updating Lat/Lon for Brodie

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-metadata#327]
Latitude and longitude for the Brodie dataset in the NMDC has limited significant digits (4 places after the decimal). I found the metadata for these samples from ESS DIVE ([WatershedSFA_SoilCores_IGSN_Metadata.xls](https://github.com/microbiomedata/nmdc-metadata/files/6368141/WatershedSFA_SoilCores_IGSN_Metadata.xls)) which show the lat/lon with 9 places after the decimal. This is likely an artifact of GOLD - as the lat/lon values were prepopulated from GOLD (and not provided directly by Eoin's team). 

**Why does this matter?** Brodie's samples are collected from different sites, and while they may vary by only 10s of meters, it's important to capture so that we can properly showcase his data on the portal (i.e. map). Right now they show up as being collected from a single location.

I don't know what the process is for getting these values updated, but will assign those that may need to be involved at some point. We may need to examine the lat/lon for the other 2 (and new) datasets as well to make sure lat/long values aren't rounded/truncated from recorded measurements.

**Comment by wdduncan** [comment]
Thanks for pointing this @pvangay.  If the data makes its way into GOLD, I can easily rerun my ETL or perhaps @dwinston can do an update? I don't know how difficult it would be updated the GOLD data and produce a new GOLD dump. Perhaps @jagadishcs or  @TBKReddy can provide some insights here.

**Comment by TBKReddy** [comment]
@pvangay, there is no artifact or limitation as such in GOLD that limits lat/long to four places after decimal. This is how the data arrived/submitted to GOLD.  

Yes we can update these values in GOLD now. There is already a process under way by NMDC to reach out to the PIs to seek additional metadata and get existing metadata updated. These lat/long values can be updated as part of that and then the updated values can make into the NMDC either by a new dump or via targeted updates. @jagadishcs include these updates along with any other metadata updates you get from the PI and then we can update.

**Comment by pvangay** [comment]
Thanks for clarifying @TBKReddy. 

Does it make more sense to update those values in GOLD, then have NMDC pull from GOLD? Or just update in both locations? I don't know the answer to this and hope those watching this issue will decide. @mslarae13 will let Eoin and his group know about the updated values from ESS DIVE when ready. Thanks all.

**Comment by dwinston** [comment]
@wdduncan @TBKReddy are there any encoding issues we may need to be careful about in GOLD or in the NMDC ETL? 

I notice, for instance that the NMDC schema lat/lon numeric properties both have a range of "decimal degree", which is [rightly identified](https://github.com/microbiomedata/nmdc-schema/blob/5a5e52f9d7198fb10f1af77a2487d9d966cbd636/src/schema/core.yaml#L53) as the `xsd:decimal` type for an RDF interpretation, but worryingly identified as a `float` type for e.g. Python use. IEEE 754 floating-point arithmetic may not accurately preserve the nine significant figures that @pvangay has observed. So we need to ensure that these fields are encoded as native decimal types (e.g. `decimal.Decimal` in python), or as string literals and only coerced to numeric forms during processing steps.

**Comment by TBKReddy** [comment]
@pvangay we will update these values in GOLD and then NMDC will pull these updates during the next data dump. 

@jagadishcs will be checking with the PIs about some other metadata. I think they indicated updates to sample collection date. All these will be updated together in GOLD.

**Comment by mslarae13** [comment]
@TBKReddy @pvangay  
I just want to confirm before I email Eoin. We are updateding the lat_long in GOLD, which will then by proxy update the information in the NMDC. And we're doing this to reflect the more accurate lat_long provided to ESS-Dive. 

Correct?

**Comment by mslarae13** [comment]
We are holding off on sending an email. Elisha is coordinating with each of the 3 PIs from the GSP push to establish their data landing pages. At this meeting we will slate some time to confirm sample metadata for all 3 projects & inquire about Brodie depths & lat-long.

**Comment by mslarae13** [comment]
Meeting update

1. Eoin & team are good with us updating GOLD & NMDC with Lat_Lon to match their IGSNs with more decimal places.
2. The correct depth is referring to the units. The header said meters. But their depth is in cm. .. this also needs to allow for a range value. (this is a larger issue to address)

Not sure what the remaining blocker is but we have answers to move forward!

**Comment by TBKReddy** [comment]
Send us the original excel with these updates, so that we can make these updates in GOLD. 

Depth range is not a problem in GOLD, because we already supporting range. For example, the biosample came up in your discussions with Eoin (https://github.com/microbiomedata/nmdc-metadata/issues/355) already in GOLD with a range. Ex: https://gold.jgi.doe.gov/biosample?id=Gb0191689

**Comment by mslarae13** [comment]
## Posting this same comment across multiple GitHub tickets encompassing corrects to be made in GOLD, correct spreadsheets, and issues to still be sorted.
@pvangay @dehays @jagadishcs 

Brodie
- Correct sheet: https://drive.google.com/file/d/1aRJhuTX7bxf1LRH8F7qK5jYpoca7-kdQ/view?usp=sharing
- Fields to correct/add
- -- Depth units should be cm, not m.
- -- Depth range, not single digit (https://github.com/microbiomedata/nmdc-metadata/issues/355)
- -- Latitude & Longitude updated to match IGSNs
- -- IGSN was added, can this be included?
- -- Ecosystem subtype (Column N), Specific ecosystem (Column O), Habitat (Column P) were updated.
- -- PI added Elevation
- Note: Matching IGSNs or ParentSample IDs indicates the same JGI and EMSL sample. Metadata is the same across these matching samples, even though it's not repeated in the "EMSL" row
- I don't believe there are any additional questions about the SAMPLE METADATA. @jagadishcs  can you confirm?
- There's some sorting to be done with the FTICR / Organic Matter data files. @corilo and I are working on that.


Wrighton
- Correct sheet: https://drive.google.com/file/d/1YiDWPxAEhpctuxuzsqBrWu2MmV_gyt83/view?usp=sharing
- Fields to correct/add
- --sample_collection_site (column J), not all samples are HRC-FS. How should we handle these? Exclude until we have clarification? Update relevant/correct samples?
- Updated columns: N, P, U-Y, AB-AJ, AK, AL, AR, AT, BI, 
- Note: No JGI -> EMSL sample mapping has been accomplished. Waiting to hear back from Reb.
- Note: Many of the fields listed in updated columns are updated for some samples but list NA/ not measured for other samples. Need to determine how to update this.
- -- See https://docs.google.com/document/d/1B1YZK2-0mBbTuRwTEJH9qkWvNerGeHvH3gbmgQML13E/edit?usp=sharing
- -- Waiting for Reb to respond with EMSL project #, associated sample analyses, and a sample list/map. Once we receive that, we can follow up on the questions in this document.


Stegen
- Correct: https://drive.google.com/file/d/1NrTWTWV39nqvy4ftq3LLQu9rF0dHBsZ-/view?usp=sharing
- Updated columns: J, P, T, U
- --Depth, column T, is in meters. centimeters would be better, and needs a range value like Stegen.
- See https://docs.google.com/document/d/1in7uAM9CjCu-5vr572hr-MoIyjDwOaP-4yry72V1MFU/edit?usp=sharing
- -- There are a few follow up questions
- -- Most important, relates to the sand mesocosms. I'm not sure if there were treatments applied to these that wasn't captured.

**Comment by dehays** [comment]
Updating lat/long from Brodie sample information has been applied in GOLD and reflected in GOLD DB export
