### ISSUE TITLE
FICUS follow up and next steps

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#329]
This issue is to document the work that Montana has been doing in April.

**Comment by ssarrafan** [comment]
@mslarae13 you mentioned you wanted this in the April sprint since you were working on it. Can this issue be closed?  Or would you like me to move it to the May sprint?

**Comment by mslarae13** [comment]
It's still active. I think we should move it to May. And provided users are quick to respond it should be finished in May.

**Comment by mslarae13** [comment]
Next steps and follow ups completed. Waiting on response from a few PIs. see: https://github.com/microbiomedata/nmdc-metadata/issues/334
