### ISSUE TITLE
FICUS metadata collection and communication

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#334]
Collecting any additional metadata before wrapping this up.

**Comment by mslarae13** [comment]
Update:
Colwell:  Responded with metadata, but no sample map
Hess: Will follow up early June
Neumann: Sent response, on Montana's to do list to follow up

No one else has responded. June 17th I'll send a follow up email stating we're planning to complete these projects the end of June, and if they're interested in being part of the next set of data searchable via NMDC, we will need the metadata and sample mapping information before the end of the month.

**Comment by mslarae13** [comment]
Update

1. Bowen: 05/27: Followed up, still working

2. Brodie: updates needed see: 
[https://github.com/microbiomedata/nmdc-metadata/issues/355](url)
[https://github.com/microbiomedata/nmdc-metadata/issues/356](url)
[https://github.com/microbiomedata/nmdc-metadata/issues/327](url)
[https://github.com/microbiomedata/nmdc-metadata/issues/340](url)
[https://github.com/microbiomedata/nmdc-metadata/issues/341](url)
 & notes from meeting [https://docs.google.com/document/d/1BNMvESw4Mm-09w_kKI6S28CnaIBrHgO52USne90bKDo/edit?usp=sharing](url)

3. Stegen: updates needed see
[https://github.com/microbiomedata/nmdc-metadata/issues/352](url)
[https://github.com/microbiomedata/nmdc-metadata/issues/351](url)
& notes from meeting: [https://docs.google.com/document/d/1RuUQJq0HRs_hbypcd-Su3v90wTevzrdcfi7xrQScdgM/edit?usp=sharing](url)

4. Colwell: User sent back metadata, but no sample mapping. Did not respond to 05/18 follow up

5. Hess: 04/23: Requested to send data early June, will follow up.

6. Neumann: received metadata info, need to follow up with more information once samples are better sorted

7. Crump: No response to any emails. (Drop)

**Comment by mslarae13** [comment]
Communications & decisions complete closing this, Creating issues for Bowen, Hess, and Neumann

**Comment by mslarae13** [comment]
Update:

1. Bowen: 07/29- I sent a follow up asking for the metadata
2. Colwell: Sent followup asking for sample ID map on 04/26, 05/10, and 05/18. No response to any messages. @emileyfadrosh  should I poke again? Or drop it?
3. Hess: 07/01- Sent follow up asking for metadata. I sent another on 07/29
4. Neumann: Transposed metadata to NMDC template, identified sample IDs and like samples between JGI and EMSL. Sent template on 07/29 asking for more detail.

Dropped
Crump: No response to any emails.
Blanchard: No response to any emails.
Rich & Firestone: Dropped per Emiley's request
