### ISSUE TITLE
SFA - Confirm metadata template design & gather feedback on usability

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#337]
This issue the the next step in the development of metadata templates for new sample environments.

**Comment by mslarae13** [comment]
Note: 
- SFA and NCBI template being reconciled & combined
- MIxS terms needed for soil packages that can be settled using plant_assoc terms
-

**Comment by mslarae13** [comment]
GSC ticket: https://github.com/GenomicsStandardsConsortium/mixs/issues/133

**Comment by mslarae13** [comment]
Updated version of template : https://docs.google.com/spreadsheets/d/1iuCyMjef97wl_Lsu1B9R4zAqrR7gfwftNKvx8LZnbW4/edit?usp=sharing

@jagadishcs : Do you have GOLD paths for sediment, plant, and water?

**Comment by jagadishcs** [comment]
@mslarae13 
Please refer to the [mapping](https://docs.google.com/spreadsheets/d/1J7cwpwOgxCXD8F_rzbvVoETrNIoaHwvAZN-Ki8i3Ku8/edit#gid=1487521647) of GOLD ecosystem classification paths with MIxS environmental packages. This file contains all of the GOLD paths (as on March 18, 2021) mapped to MIxS packages.

**Comment by mslarae13** [comment]
Thanks @jagadishcs ! Next question, when you developed the drop down lists for the FICUS project metadata template for soil fao_class, tillage, horizon, ect... did you just use the MIxS terms  that were listed as options? Or did you curate anything yourself?

**Comment by jagadishcs** [comment]
@mslarae13 
For all of the MIxS CV fields, I just used the terms that are provided in the specific MIxS packages & specific fields.

**Comment by mslarae13** [comment]
Version update:
NMDC: https://docs.google.com/spreadsheets/d/1Glb9pWmV5H9UrI_oeC-eMxvzzmZKGALjh2FL-uRWI_o/edit?usp=sharing


NCBI-NMDC:  https://docs.google.com/spreadsheets/d/1EErq7CmBJ7779qAt8ysnN_zpOgxxvwPxEEsSXDXCuOw/edit?usp=sharing

**Comment by ssarrafan** [comment]
@mslarae13 thank you for putting in the links.  Can this issue be closed?

**Comment by mslarae13** [comment]
Template layout confirmed. Soil complete.
The "feed back" part of this task will start soon. I am going to close this one and create 2 new tasks in the June sprint.
