### ISSUE TITLE
Updates to Wrighton metadata

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-metadata#342]
@mslarae13 and I met with Reb Daly from the Wrighton group today to review their data in the portal.

### **Sample names need to be renamed to something that is not the Proposal name.** 
Suggest using IDs of some sort. This is misleading because not all samples are "deep subsurface shale", which just happens to be the name of the proposal.

### Can we reclassify these samples into their correct environments (GOLD and EnvO)? 
Probably need to make sure these are corrected upstream as well (GOLD). Sample names with:
- LW = Fresh Water (from a lake nearby)
- HT = Holding Tank (Fresh water that's in a holding tank before being mixed with chemicals)
- FC or FF = Fresh water mixed with fracking chemicals (this get pumped into the shale for fracking)
- All other samples are time series samples of the fluid post-fracking

### **Remove all of these samples, as they're isolates that were used in the study but not microbiome samples**
- Deep subsurface shale carbon reservoir microbial communities from Ohio, USA - WG8 viral induction
- Deep subsurface shale carbon reservoir microbial communities from Ohio, USA - Halanaerobium induction
- Deep subsurface shale carbon reservoir microbial communities from Ohio, USA - Methanogen_OWC (+ methanogen enrichment)
- Deep subsurface shale carbon reservoir microbial communities from Ohio, USA - Methanotroph_Enrichment_5
- Deep subsurface shale carbon reservoir viral communities from Ohio, USA - WG14 viral induction ssDNA
- Deep subsurface shale carbon reservoir microbial communities from Ohio, USA - LMS_cellobiose_enrichment

Tagging @dehays as this is related to finding a way to edit NMDC metadata - please reference the relevant issues this should be associated with. Should this issue also be assigned to you?

Adding as listeners: @kfagnan @dwinston

**Comment by ssarrafan** [comment]
@dehays I was discussing this with @pvangay  and we added it to the sprint to see if it can be worked on since it will help with some of the other portal related fixes.  Let us know if it shouldn't be in this sprint or if it should be assigned to someone else.

**Comment by dehays** [comment]
The decision here is to either 1) make the changes in GOLD and then propagate to NMDC or 2) make the change in NMDC and alert GOLD to update biosample records there.

**Comment by pvangay** [comment]
@mslarae13 please add a link to wrighton's latest metadata spreadsheet as some of these details may already be captured there

**Comment by mslarae13** [comment]
Posting this same comment across multiple GitHub tickets encompassing corrects to be made in GOLD, correct spreadsheets, and issues to still be sorted.
@pvangay @dehays @jagadishcs

Brodie

Correct sheet: https://drive.google.com/file/d/1aRJhuTX7bxf1LRH8F7qK5jYpoca7-kdQ/view?usp=sharing
Fields to correct/add
-- Depth units should be cm, not m.
-- Depth range, not single digit (#355)
-- Latitude & Longitude updated to match IGSNs
-- IGSN was added, can this be included?
-- Ecosystem subtype (Column N), Specific ecosystem (Column O), Habitat (Column P) were updated.
-- PI added Elevation
Note: Matching IGSNs or ParentSample IDs indicates the same JGI and EMSL sample. Metadata is the same across these matching samples, even though it's not repeated in the "EMSL" row
I don't believe there are any additional questions about the SAMPLE METADATA. @jagadishcs can you confirm?
There's some sorting to be done with the FTICR / Organic Matter data files. @corilo and I are working on that.
Wrighton

Correct sheet: https://drive.google.com/file/d/1YiDWPxAEhpctuxuzsqBrWu2MmV_gyt83/view?usp=sharing
Fields to correct/add
--sample_collection_site (column J), not all samples are HRC-FS. How should we handle these? Exclude until we have clarification? Update relevant/correct samples?
Updated columns: N, P, U-Y, AB-AJ, AK, AL, AR, AT, BI,
Note: No JGI -> EMSL sample mapping has been accomplished. Waiting to hear back from Reb.
Note: Many of the fields listed in updated columns are updated for some samples but list NA/ not measured for other samples. Need to determine how to update this.
-- See https://docs.google.com/document/d/1B1YZK2-0mBbTuRwTEJH9qkWvNerGeHvH3gbmgQML13E/edit?usp=sharing
-- Waiting for Reb to respond with EMSL project #, associated sample analyses, and a sample list/map. Once we receive that, we can follow up on the questions in this document.
Stegen

Correct: https://drive.google.com/file/d/1NrTWTWV39nqvy4ftq3LLQu9rF0dHBsZ-/view?usp=sharing
Updated columns: J, P, T, U
--Depth, column T, is in meters. centimeters would be better, and needs a range value like Stegen.
See https://docs.google.com/document/d/1in7uAM9CjCu-5vr572hr-MoIyjDwOaP-4yry72V1MFU/edit?usp=sharing
-- There are a few follow up questions
-- Most important, relates to the sand mesocosms. I'm not sure if there were treatments applied to these that wasn't captured.

**Comment by ssarrafan** [comment]
@pvangay said this should move to the July sprint so moving this one.

**Comment by pvangay** [comment]
Looks like almost everything was addressed, except the moose gut sample.

**Comment by pvangay** [comment]
Moose gut was updated post ETL for the July release (https://github.com/microbiomedata/nmdc-runtime/issues/11#issuecomment-876853472) and will get further corrected with more accurate values in GOLD. This will get updated in future data dumps.
