### ISSUE TITLE
Update Brodie dataset citation text

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-metadata#343]
Update the dataset citation on [Eoin's landing page](https://data.microbiomedata.org/details/study/gold:Gs0135149) to: 
Sorensen, P., Brodie, E., Beller, H., Wang, S., Bill, M., & Bouskill, N. (2019). Sample Collection Metadata for Soil Cores from the East River Watershed, Colorado collected in 2017 [Data set]. ESS-DIVE. https://doi.org/10.21952/WTR/1573029

@dehays should this edit be done further upstream as well? FYI, this was a request from Joan at ESS DIVE (since this is an ESS DIVE dataset citation)

**Comment by dwinston** [comment]
via microbiomedata/nmdc-runtime@e206ff7f50f2300c5dbd6dfea520f221da73da3b
