### ISSUE TITLE
Sample Metadata Training materials

### ISSUE THREAD

**Issue by elishawc** [microbiomedata/nmdc-metadata#345]
Develop slides and activity for community training sessions related to sample metadata

**Comment by elishawc** [comment]
Shared "final" draft slides with broader training community representative for feedback and discussion around next steps. Slides here: https://docs.google.com/presentation/d/1hs9OROPTuB6ZUXTvmAj9hihGYlQ1XLkhNWF4rnBDSC8/edit?ts=60a34533#slide=id.p1

**Comment by ssarrafan** [comment]
Closing per @elishawc
