### ISSUE TITLE
Python expertise help for Bill and Donny

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#346]
This issue is related to issue [312](https://github.com/microbiomedata/nmdc-metadata/issues/312) and issue 309: https://github.com/microbiomedata/nmdc-metadata/issues/309
This issue is assigned to Emiley and Set to get some help for Python expertise.

**Comment by dwinston** [comment]
From the email conversation with Patrick Chain, it seems that this requires identification of particular tasks and issues. I have made a [python](https://github.com/microbiomedata/nmdc-runtime/labels/python) tag in the nmdc-runtime repo for annotating these as they become apparent. Also, it seems that completing #347 would be a prerequisite for such help.

**Comment by ssarrafan** [comment]
Since completing #347 is a prerequisite and that can't be done till June I'm moving this to the June sprint.  Chris did offer some help from Mark too.

**Comment by emileyfadrosh** [comment]
Discussed with @cmungall and will have additional support from his team. Will need issues clearly assigned.
