### ISSUE TITLE
Map GOLD ecosystem paths to ENVO

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#35]
cc @kaiiam @pbuttigieg

**Comment by kaiiam** [comment]
I sent you the GOLD paths mapping to MIxS style ENVO triads. It should work for your first pass. If I can get some funding to work on NMDC I can help this effort in the future.

**Comment by wdduncan** [comment]
I integrated what you sent with other GOLD path info. see:

https://docs.google.com/spreadsheets/d/1Tfbj0QCckk_S6ldyVJZcTdJKZHd1D9Y4whWz2CjeIcI/edit#gid=1310900750

**Comment by dehays** [comment]
@wdduncan  What is the scope of this issue?  Does this include all GOLD biosample environment paths or the subset of paths present in samples for the FICUS studies?

**Comment by wdduncan** [comment]
@dehays Ultimately, it is all GOLD paths. Currently, we are focusing on the FICUS studies.

**Comment by wdduncan** [comment]
Update: Jagadish has completed mapping biosample GOLD paths to MIxS triads for the FICUS studies.
