### ISSUE TITLE
Recheck sample and omics linkages for Stegen dataset

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-metadata#351]
This may be related to https://github.com/microbiomedata/nmdc-metadata/issues/341

@mslarae13 and I met with James today to review his data in the portal. He thinks that every sample that has NOM should also have metaG. The numbers for the omics types do not seem to match what he thinks they should be. 1111 for NOM and 121 for metaP seems especially high.

**Comment by dehays** [comment]
Using updated EMSL dataset lists (see #341) likely will reduce the number of NOM listed for Stegen.  The 121 count for metaP is also coming from the total number of instrument runs (EMSL datasets).  I know the number of metaP instrument datasets for which any analysis workflow was applied is much lower as the workflow requires matching to metaG annotation.  Meaning, if we should make a decision to only include metaP instrument runs for which there is NMDC analysis, that number comes way down too.

**Comment by mslarae13** [comment]
Posting this same comment across multiple GitHub tickets encompassing corrects to be made in GOLD, correct spreadsheets, and issues to still be sorted.
@pvangay @dehays @jagadishcs

Brodie

Correct sheet: https://drive.google.com/file/d/1aRJhuTX7bxf1LRH8F7qK5jYpoca7-kdQ/view?usp=sharing
Fields to correct/add
-- Depth units should be cm, not m.
-- Depth range, not single digit (#355)
-- Latitude & Longitude updated to match IGSNs
-- IGSN was added, can this be included?
-- Ecosystem subtype (Column N), Specific ecosystem (Column O), Habitat (Column P) were updated.
-- PI added Elevation
Note: Matching IGSNs or ParentSample IDs indicates the same JGI and EMSL sample. Metadata is the same across these matching samples, even though it's not repeated in the "EMSL" row
I don't believe there are any additional questions about the SAMPLE METADATA. @jagadishcs can you confirm?
There's some sorting to be done with the FTICR / Organic Matter data files. @corilo and I are working on that.
Wrighton

Correct sheet: https://drive.google.com/file/d/1YiDWPxAEhpctuxuzsqBrWu2MmV_gyt83/view?usp=sharing
Fields to correct/add
--sample_collection_site (column J), not all samples are HRC-FS. How should we handle these? Exclude until we have clarification? Update relevant/correct samples?
Updated columns: N, P, U-Y, AB-AJ, AK, AL, AR, AT, BI,
Note: No JGI -> EMSL sample mapping has been accomplished. Waiting to hear back from Reb.
Note: Many of the fields listed in updated columns are updated for some samples but list NA/ not measured for other samples. Need to determine how to update this.
-- See https://docs.google.com/document/d/1B1YZK2-0mBbTuRwTEJH9qkWvNerGeHvH3gbmgQML13E/edit?usp=sharing
-- Waiting for Reb to respond with EMSL project #, associated sample analyses, and a sample list/map. Once we receive that, we can follow up on the questions in this document.
Stegen

Correct: https://drive.google.com/file/d/1NrTWTWV39nqvy4ftq3LLQu9rF0dHBsZ-/view?usp=sharing
Updated columns: J, P, T, U
--Depth, column T, is in meters. centimeters would be better, and needs a range value like Stegen.
See https://docs.google.com/document/d/1in7uAM9CjCu-5vr572hr-MoIyjDwOaP-4yry72V1MFU/edit?usp=sharing
-- There are a few follow up questions
-- Most important, relates to the sand mesocosms. I'm not sure if there were treatments applied to these that wasn't captured.
