### ISSUE TITLE
Generate sample metadata description of header rows

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-metadata#359]
Mark & Bill requested detailed information about the columns and components of the metadata to make a "map" or SSSOM.

**Comment by mslarae13** [comment]
@turbomam @wdduncan 
Do you also need to know what sample types will have each component? Or does that matter?
For example, plant_struct is only in plant.

**Comment by mslarae13** [comment]
https://docs.google.com/spreadsheets/d/1IXFhklF1PyF6mqXuJo9mu6QrTvnEvWI1JV52TOHJphc/edit?usp=sharing

**Comment by turbomam** [comment]
> @turbomam @wdduncan
> Do you also need to know what sample types will have each component? Or does that matter?
> For example, plant_struct is only in plant.

Good question. Right now, I would say "no" for me, but I might be overlooking something.

@wdduncan , would the ENVO term subsetting for MIxS triads apply to this potential sample type/component alignment.

**Comment by mslarae13** [comment]
@turbomam  @wdduncan 

Have you had a chance to look these over? I am going to close this issue and make a follow up for you two to look it over & us meet and discuss next steps. Maybe this would be a good agenda item for out metadata related meetings on wednesdays?
