### ISSUE TITLE
Identify necessary Project information components

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-metadata#366]
See - https://docs.google.com/spreadsheets/d/10TU3E-TAbtzeo-_S8rYfSq8Xvp6wm1RMpo0LYtR4t9w/edit?usp=sharing 

ReadMe -> Project Information section (details from GOLD or added per meeting conversation)

Everyone, could you please information what components here are not necessary, what needs added, and add definitions to components with ??, as I am not familiar with how to identify these.

@wdduncan & @turbomam - Using the information in the row ID and definition, are these matching to what's in the schema now, if not can we add them, and if they're in the schema but with a different name can you provide me with this names?

Please Comment with suggestions, changes, or questions. Reminder, you need to do this in G-SHEET. 
Please check you box when you've complete your review of ProjectInformation

- [x] @wdduncan 
- [x] @turbomam 
- [x] @emileyfadrosh 
- [x] @elishawc 
- [x] @pvangay 
- [x] @dehays

**Comment by wdduncan** [comment]
I made comments, but unfortunately. I am not familiar with things like NCBI Umbrella Projects.

**Comment by elishawc** [comment]
There are a few terms we might need to talk thru. Made some comments. 
e.g., investigation_type - that was a term in v5, which was deprecated in v6. I don't think we should try to include it with new CV, as it will make back-compatibility really confusing. Also, if pink is mandatory, I think there are a few fields (growth_facil) that shouldn't be mandatory.

**Comment by mslarae13** [comment]
I commented back with any questions I had, and made indicated changes where I could.
If responses to these comments aren't addressed, could we spend some time this Wednesday at the Aim 1 meeting to discuss?

 @wdduncan
 @turbomam
 @emileyfadrosh
 @elishawc
 @pvangay
 @dehays

**Comment by mslarae13** [comment]
Updated and corrected based on discussion & comments from Wednesday's meeting. 

See: https://docs.google.com/spreadsheets/d/10TU3E-TAbtzeo-_S8rYfSq8Xvp6wm1RMpo0LYtR4t9w/edit?usp=sharing
