### ISSUE TITLE
Project/study page and available metadata for BioScales project

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#370]

**Comment by dehays** [comment]
Additional metadata values that are not available from GOLD but are used by the UI will need to be added to post ETL ( see microbiomedata/nmdc-schema#51 )

**Comment by dehays** [comment]
Study and samples are included in GOLD DB export.  Will need to set values for web sites, profile_image_url, title, scientific objective post-ETL.

**Comment by ssarrafan** [comment]
@dehays @emileyfadrosh I'm assuming this issue should move to July but please confirm.

**Comment by emileyfadrosh** [comment]
Had a meeting with BioScales team earlier today and update from JGI is to expect ~200 metagenomes to be ready in the next couple weeks. Suggest adding new tickets to (1) schedule call and collect additional metadata from the BioScales team and (2) develop plan for pulling data from JGI production.
