### ISSUE TITLE
Unclassified ecosystem subtype with specific ecosystem value

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#38]
@cmungall 
We need to determine the meaning of GOLD classifications in which the ecosystem subtype is unclassified, but the the specific ecosystem has a value.

There aren't many of them (~17). See screenshot. But, in general, what does the value 'Unclassified' mean? Does it mean 'missing' or 'unknown' or something else?

I am hoping @jagadishcs can shed light on this.

<img width="1087" alt="Screen Shot 2020-02-10 at 4 51 17 PM" src="https://user-images.githubusercontent.com/3186638/74204235-31227a00-4c27-11ea-8331-7968174c0e90.png">

**Comment by jagadishcs** [comment]
![image](https://user-images.githubusercontent.com/54855373/74303441-b0d74400-4d0e-11ea-99b1-8a66f1091dbd.png)

**Comment by wdduncan** [comment]
@jagadishcs  Thanks for the explanation!
I'm going to close this issues.
