### ISSUE TITLE
Pull down the metadata from NCBI: PRJEB39497 (metaG), PRJEB39495 (16S rRNA), PRJEB39496 (fungal ITS)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-metadata#381]
TES SFA team asked for help pulling down the metadata from NCBI: PRJEB39497 (metaG), PRJEB39495 (16S rRNA), PRJEB39496 (fungal ITS). Ricardo will review it in detail, and follow up with the appropriate people to fill in any gaps. He says that he does not have access to all of the original metadata that was submitted to NCBI - so asked for our help in pulling it down so that he can review it with the other metadata that he does have in the SFA. Hope this makes sense. Please let me know if you have any questions.

**Comment by ssarrafan** [comment]
@jagadishcs please let @emileyfadrosh know if you have any questions about this request.  Would it be possible to get this done by early next week?

**Comment by ssarrafan** [comment]
@jagadishcs @emileyfadrosh 

We had our mid-sprint review today so I'm checking in with folks who have issues for this sprint to see if you need help with anything, are blocked by anything or have any concerns about completing your issue by the end of July.  Let me know if there are any concerns.

**Comment by jagadishcs** [comment]
The BioSample metadata from BioProjects PRJEB39495, PRJEB39496 and PRJEB39497 are made available [here](https://drive.google.com/drive/folders/1KBflo3OmH-Sm3YWJp8OK3rWKyOGr1D8o) using the latest NMDC metadata template. 
The data available as it is in NCBI has been included in a separate tab for each project.

**Comment by ssarrafan** [comment]
@jagadishcs and @emileyfadrosh can we close this GitHub issue?

**Comment by jagadishcs** [comment]
Hi @pvangay, do you want to communicate Ricardo the [metadata](https://drive.google.com/drive/folders/1KBflo3OmH-Sm3YWJp8OK3rWKyOGr1D8o) shared and suggest closing this GitHub issue?

**Comment by emileyfadrosh** [comment]
@ssarrafan I think we can close this, and @pvangay can contact Ricardo when she is back in the office. Thanks, @jagadishcs!
