### ISSUE TITLE
some biosamples not part_of a study

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-metadata#382]
There are 40 documents in `biosample_set` that have no `part_of` field (shown below. This is allowed schema-wise, as `part_of` is not a required field. I want to verify that this is okay, or if this is an issue.

```
# db.biosample_set.distinct('id', {part_of: {$exists: false}})
[
    "emsl:63ca2c7e-6647-11eb-ae93-0242ac130002",
    "emsl:63ca2eae-6647-11eb-ae93-0242ac130002",
    "emsl:63ca2f94-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3070-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3340-6647-11eb-ae93-0242ac130002",
    "emsl:63ca341c-6647-11eb-ae93-0242ac130002",
    "emsl:63ca34da-6647-11eb-ae93-0242ac130002",
    "emsl:63ca358e-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3642-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3700-6647-11eb-ae93-0242ac130002",
    "emsl:63ca37b4-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3868-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3b1a-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3d04-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3dc2-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3e76-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3f2a-6647-11eb-ae93-0242ac130002",
    "emsl:63ca3fd4-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4088-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4146-6647-11eb-ae93-0242ac130002",
    "emsl:63ca443e-6647-11eb-ae93-0242ac130002",
    "emsl:63ca459c-6647-11eb-ae93-0242ac130002",
    "emsl:63ca46fa-6647-11eb-ae93-0242ac130002",
    "emsl:63ca47e0-6647-11eb-ae93-0242ac130002",
    "emsl:63ca489e-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4952-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4a38-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4aec-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4d4e-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4e02-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4eb6-6647-11eb-ae93-0242ac130002",
    "emsl:63ca4f6a-6647-11eb-ae93-0242ac130002",
    "emsl:63ca5014-6647-11eb-ae93-0242ac130002",
    "emsl:63ca50c8-6647-11eb-ae93-0242ac130002",
    "emsl:63ca517c-6647-11eb-ae93-0242ac130002",
    "igsn:IEWFS000A",
    "igsn:IEWFS000B",
    "igsn:IEWFS000I",
    "igsn:IEWFS000J",
    "igsn:IEWFS000K"
]
```

**Comment by dehays** [comment]
On a biosample - I think we should consider making part_of required and not permit an empty list value.  @wdduncan 

The reason that these samples have no study association is because that association was set in the GOLD ETL and that process knows nothing about these samples that were never in GOLD.  These samples were added post GOLD ETL based on Stegen and Brodie data provided by Montana / EMSL.  Each should be the input of metaP, metaB or NOM processing - so we should be able to set the study in the biosample part_of by looking at the omics_processing part_of.

**Comment by dwinston** [comment]
okay, looking into using `omics_processing.part_of` as fallback to set `biosample.part_of` for these.

**Comment by dehays** [comment]
@dwinston I can take care of the 5 EMSL only samples.  In addition to the part_of value there are issues with the sample names and possibly the dates.  I'll have a PR for you in a few minutes.

**Comment by dwinston** [comment]
okay. FYI I found `db.omics_processing.count_documents({"has_input": {"$in": ids_biosamples__no_part_of}})` to be zero (as well as `db.omics_processing.count_documents({"part_of": {"$in": ids_biosamples__no_part_of}})`, but this latter query should match studies and not biosamples, so I expect a count of zero).

**Comment by dwinston** [comment]
> Each should be the input of metaP, metaB or NOM processing

Also got zero results for
```
db.metabolomics_analysis_activity_set.count_documents({"has_input": {"$in": ids_biosamples__no_part_of}})
db.metaproteomics_analysis_activity_set.count_documents({"has_input": {"$in": ids_biosamples__no_part_of}})
db.nom_analysis_activity_set.count_documents({"has_input": {"$in": ids_biosamples__no_part_of}})
```
