### ISSUE TITLE
Add project category to JSON based on sequencing_strategy from GOLD project table

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#39]
Each project entity needs to include a category which is available from the SEQUENCING_STRATEGY field of the PROJECT table in GOLD.

The only two values we should see from GOLD for the FICUS project metadata are:

Metagenome
Metatranscriptome

(EMSL will be providing 4 additional categories for their projects)

**Comment by wdduncan** [comment]
There is also field called `sequencing_strategy_full`. Do you know the difference?
perhaps @jagadishcs does?

**Comment by wdduncan** [comment]
To follow up:
This query:
```
select distinct SEQUENCING_STRATEGY from PROJECT
```
returns:
```
Metagenome
Targeted Gene Survey
Metatranscriptome
Whole Genome Sequencing
Transcriptome
```

This query:
```
select distinct SEQUENCING_STRATEGY_FULL from PROJECT
```
returns:
```
Metagenome
Targeted Gene Survey
Metatranscriptome
Whole Genome Sequencing
Transcriptome
Metagenome - Cell Enrichment
```
So, the difference is the `Metagenome - Cell Enrichment` value. Does this matter?

**Comment by dehays** [comment]
I’d thought the SEQUENCING_STATEGY_FULL  field would be more specific than
SEQUENCING_STATEGY.  I hadn’t expected them to overlap.

What you have in your PROJECT table is only the 913 FICUS projects?  I’m
really curious about the projects that are neither Metagenome or
Metatranscriptome

David

**Comment by wdduncan** [comment]
Based on Reddy's comments at the meeting today (2/12/2020), we should use the `SEQUENCING_STRATEGY` field.
