### ISSUE TITLE
ingest metadata from EMSL

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-metadata#42]
The EMSL instrument run metadata has been added as Excel spreadsheet here:

https://drive.google.com/drive/u/0/folders/1frzGlz8EB8inpVokNTSwD6Ia94eVUlsZ

Mapping is currently to EMSL proposal ID which we need to map to the GOLD study IDs 

These include the omics type (proteomics, metabolomics, ...) field.   

We need to select which fields to map into our project and data_object JSON

**Comment by wdduncan** [comment]
The only EMSL proposal ID that I find in the spreadsheet is 49991. This doesn't seem to map to any of the study gold ids I have:
Gs0114432
Gs0114663
Gs0114298
Gs0111539
Gs0110148
Gs0110115
Gs0110132
Gs0110198
Gs0121594
Gs0112340
Gs0128781
Gs0114675
Gs0133461
Gs0128849
Gs0130354
Gs0135149
Gs0135152
Gs0134277
Gs0120351

**Comment by dehays** [comment]
@wdduncan Find the mapping from EMSL proposal ID to GOLD Study ID here:  [](https://docs.google.com/spreadsheets/d/1BX35JZsRkA5cZ-3Y6x217T3Aif30Ptxe_SjIC7JqPx4/edit)

**Comment by wdduncan** [comment]
Hi @dehays to summarize action items from our call:

* Change `sequencing_strategy` to `omics_type`.
* Create an `omics processing` entity (subtype of `biosample processing`) in which to represent GOLD sequencing projects as well as instrument runs from EMSL.
* Proposed characteristics for omics processing entities from EMSL:
  - `Dataset ID` to be used as the identifier for the process.
  -  `Dataset Type Description` (e.g., "High resolution MS spectra only")
  - `Instrument Name` (e.g., "12T_FTICR_B")
  - `Experimental Data Type`: This will be called `omics type` (e.g., "Organic Matter Characterization").
* Proposed characteristics for `data objects` that are output by EMSL `omics processing`:
  -  `Dataset File Size Bytes` (e.g., "30074294")
  -  `Dataset Name` (e.g. "Brodie_134A_CHCl3_15Oct18_IAT_p1_1_01_35922") to be used **label**?

I will also discuss with @cmungall

**Comment by dehays** [comment]
The fields of the data_object metadata I gave to Kitware generated from JAMO had the following fields:

GOLD Project ID   --> . This should map to the ids in the projects.json you have.
JAMO hash ID . --> unique file identifier
File Name . --> Not necessarily unique
Category . --> this is derived from a field used by JGI's Genome Portal
File Type --> doesn't look useful for display, I may use it to filter
File Size --> . Useful for display

From the EMSL data for a data_object, we will want to represent the omics_processing entity ID in the data_object.  So a study has one-to-many omic_preocessing things which has one-to-many data objects.  omics_processing is 1:1 with data object for EMSL but not for JGI.

I propose using the 'Data Set Name' from the EMSL spreadsheet for both the omics_processing name and for the data_object name.  (In the JGI cases, data objects have names like based on whether they represent read files or assembly files (and later types of annotation).

* Important for the omics_processing - we need a field like "processing_institution" which will be either "Joint Genome Institute" . (all the projects from GOLD) or "Environmental Molecular Sciences Lab" (all the EMSL instrument runs)

**Comment by wdduncan** [comment]
@dehays Where is the JAMO file?

**Comment by dehays** [comment]
@wdduncan Working right now to produce a set from JAMO metadata for the fastq and assemblies.

**Comment by dehays** [comment]
@wdduncan I've added a tsv (including headers) for the fastq files here:
https://drive.google.com/drive/u/0/folders/1frzGlz8EB8inpVokNTSwD6Ia94eVUlsZ

I need to query differently for the fna and faa because they have no GOLD project metadata keys in JAMO, but those tsv files will have the same fields.

**Comment by wdduncan** [comment]
EMSL data has been integrated. So, I'm going to close this.
