### ISSUE TITLE
1.2.2 First pass at mapping GOLD to ENVO

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#5]

**Comment by wdduncan** [comment]
I updated the mapping file see: `gold-env-top7-mapping.ipynb`.
I also got the code to create bipartite graphs working see: `gold-env-elevels-analysis.ipynb`

Can the bipartite approach yield interesting analysis? I'm out of my depth here regarding graph theory.

This article looks interesting: https://academic.oup.com/gigascience/article/7/4/giy014/4875933

**Comment by wdduncan** [comment]
Closing this ticket. We can track progress in #35
