### ISSUE TITLE
Register gold prefixes on identifiers.org and n2t.net

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#56]
See also #2 and https://github.com/microbiomedata/pilot/issues/16

We want to use unambiguous prefixed identifiers for entities in GOLD

Identifiers.org has an entry `gold.meta`:

https://registry.identifiers.org/registry/gold.meta

This uses legacy IDs. The example is https://identifiers.org/gold.meta:Gm00047

This redirects to a study https://gold.jgi.doe.gov/study?id=Gs0056621

Same for http://n2t.net/gold.meta:Gm00047

I think we need to register prefixes that can be used to access samples, as well as studies. I think there are two ways

 1. Register `gold.sample` and `gold.study`
 2. Register a blanker `gold` prefix, have this go to a generic URL such as https://gold.jgi.doe.gov/entity?id=Gs0056621 and have the GOLD website redirect this to the appropriate URL based on the two letter code.

I prefer 2 as it avoids proliferating prefixes

**Comment by TBKReddy** [comment]
GOLD site registered @https://registry.identifiers.org/registry/gold that let anyone connect using any of the 5 GOLD id types and straight go to that page.

**Comment by cmungall** [comment]
This is great, thanks so much!
