### ISSUE TITLE
Mapping MIxS (v5) and GOLD water biosample fields using the package specific spreadsheet

### ISSUE THREAD

**Issue by jagadishcs** [microbiomedata/nmdc-metadata#57]
@cmungall  
@wdduncan

I will be mapping water package MIxS (v5) terms with GOLD biosample fields using the package specific spreadsheet that was shared by Bill.

https://docs.google.com/spreadsheets/d/1xbSmHbzZWTUCXY4SCe3zZ6_YFxmuW4ht5s5_3jdgyyQ/edit#gid=994826157

**Comment by wdduncan** [comment]
Thanks. The MIxS water package is in this folder:

https://drive.google.com/drive/u/1/folders/13DVA0GGoypGIwzCTdKWS4eNh3Y8tjX3y

If you can't find a v5 term, you can look in the v4 spreadsheet too.

**Comment by jagadishcs** [comment]
@wdduncan 
@cmungall 

I have completed the mapping of water package and placed it in the shared folder 'GOLD Database Mappings'.
Bill, would you like to verify/validate before start using and closing the ticket.
Please let me know if you have any suggestion or question. 

https://docs.google.com/spreadsheets/d/1cfrkPF8wuyfUJ6L_byaaQ-Mly9ePBxCt6y1UqYeBBr4/edit#gid=1365761771

Thanks

**Comment by dehays** [comment]
@wdduncan @jagadishcs  Is this complete?

**Comment by jagadishcs** [comment]
@dehays 
@wdduncan 

Yes, it has been completed.
