### ISSUE TITLE
Get list of GOLD paths used for FICUS

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#58]
Hi @jagadishcs 
For FICUS projects, can you get list of the GOLD paths that are used? This will help us focus on which paths need to be the MIxS/ENVO triad of biome-material-feature.

Add @cmungall to the conversation.

**Comment by jagadishcs** [comment]
Hi @wdduncan and @cmungall 
You can please access the list of ecosystem paths by biosample for FICUS studies from here:
https://docs.google.com/spreadsheets/d/1AMMsDYPjngNAe0CaZkY8xL7Yf751r5iO4xPSj69HX1A/edit#gid=1478189118

**Comment by wdduncan** [comment]
Thanks @jagadishcs!
I did a check for the unique paths. There is a total of 15 unique path ids for use to focus on:

ECOSYSTEM_PATH_ID_Biosamples
--
4564
4287
4203
4023
4212
4533
4205
4012
4024
3937
4003
4245
4234
4206
4318

**Comment by wdduncan** [comment]
I added a tab to spreadsheet with the unique paths.
