### ISSUE TITLE
1.2.2 Gap-filling missing terms present in GOLD and not in EnvO

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#6]

**Comment by wdduncan** [comment]
We have a lot NaN and unclassified values. Do we want special class to identify unclassified data? NaN can mean missing data, while (perhaps) means the data is present, but there isn't an appropriate label/value to tag it with.

**Comment by wdduncan** [comment]
### ECOSYSTEM_TYPE values

**Comment by wdduncan** [comment]
### ECOSYSTEM_CATEGORY values (top 7 most occurring)

|    | ECOSYSTEM       | ECOSYSTEM_CATEGORY   |
|---:|:----------------|:---------------------|
|  0 | Engineered      | Built environment    |
|  1 | Engineered      | Wastewater           |
|  2 | Environmental   | Aquatic              |
|  3 | Environmental   | Terrestrial          |
|  4 | Host-associated | Human                |
|  5 | Host-associated | Mammals              |
|  6 | Host-associated | Plants               |

## proposed mappings
Engineered / Built environment -> ???  
note: unusure of the distinction 'engineered' and 'built'; perhaps a building?  
  
Engineered / Wastewater -> ???  
note: perhaps add class 'enviromental system determined by waste water' unless they mean a portion of waste water differing lables with 'enironment deterimed by' and 'enviromental system determined'; 
  
Environmental / Aquatic -> **envo:ENVO_00002030**; rdfs:label "aquatic biome"^^xsd:string **OR** **envo:ENVO_01000317**; rdfs:label "aquatic environment"  
note: not sure of the distinction between biome and enviroment here; evironment seem more general, so might be more appropropiate  
  
Environmental / Terrestrial ->  **envo:ENVO_01001226**; rdfs:label "terrestrial natural environment"@en  
  
Host-associated / Mammals -> ???  
note: perhaps add class 'mammal-associated enviroment' as subclass of 'animal-associted enviroment'
  
Host-associated / Human -> ???  
note: perhaps add class 'human-associated enviroment' as subclass of 'mammal-associated enviroment' (referrenced above)
  
Host-associated / Plants ->  **envo:ENVO_01001001**; rdfs:label "plant-associated environment"@en

**Comment by wdduncan** [comment]
### ECOSYSTEM_TYPE values (top 7 most occurring)

|    | ECOSYSTEM       | ECOSYSTEM_CATEGORY   | ECOSYSTEM_TYPE   |
|---:|:----------------|:---------------------|:-----------------|
|  0 | Engineered      | Built environment    | Unclassified     |
|  1 | Engineered      | Built environment    | City             |
|  2 | Engineered      | Wastewater           | Unclassified     |
|  3 | Environmental   | Aquatic              | Freshwater       |
|  4 | Environmental   | Terrestrial          | Soil             |
|  5 | Environmental   | Aquatic              | Marine           |
|  6 | Environmental   | Aquatic              | Unclassified     |
|  7 | Environmental   | Terrestrial          | Unclassified     |
|  8 | Environmental   | Aquatic              | Thermal springs  |
|  9 | Host-associated | Human                | Digestive system |
| 10 | Host-associated | Mammals              | Digestive system |
| 11 | Host-associated | Human                | Unclassified     |
| 12 | Host-associated | Mammals              | Unclassified     |
| 13 | Host-associated | Plants               | Unclassified     |

## proposed mappings
Engineered / Built environment / City -> **envo:ENVO_01000248**; rdfs:label "dense settlement biome" **OR** **envo:ENVO_01000249**; rdfs:label "urban biome"
note: 'city' might refer to a type of environment zone; if so, this might require adding new classes

Engineered / Wastewater / Unclassified ->  ???  
note: Do we want special class to identify unclassified data?  

Environmental / Aquatic / Freshwater -> **envo:ENVO_01000306**; rdfs:label "freshwater environment"  

Environmental / Terrestrial / Soil -> **envo:ENVO_01001044**; rdfs:label "soil environment"@en

Environmental / Aquatic / Marine -> **ENVO_01000307**; rdfs:label "saline water environment"  

Environmental / Aquatic / Unclassified -> ???  
note: Do we want special class to identify unclassified data?  

Environmental / Terrestrial / Unclassified -> ???  
note: Do we want special class to identify unclassified data?  

Environmental / Aquatic / Thermal springs -> ???  
note: add as subclass of 'aquatic environment'  

Host-associated / Mammals / Digestive system -> ???  
note: add class 'mammalian digestive tract enviroment' as subclass of 'digestive tract environment'  

Host-associated / Human / Digestive system -> ???  
note: note: add class 'human digestive tract environment' as subclass of 'mammalian digestive tract environment' (referenced above)  

Host-associated / Human / Unclassified -> ???  
note: Do we want special class to identify unclassified data?  

Host-associated / Mammals / Unclassified -> ???  
note: Do we want special class to identify unclassified data?  

Host-associated / Plants / Unclassified -> ???  
note: Do we want special class to identify unclassified data?

**Comment by wdduncan** [comment]
### ECOSYSTEM_SUBTYPE values (top 7 most occurring)

|    | ECOSYSTEM       | ECOSYSTEM_CATEGORY   | ECOSYSTEM_SUBTYPE   |
|---:|:----------------|:---------------------|:--------------------|
|  0 | Engineered      | Built environment    | Unclassified        |
|  1 | Engineered      | Wastewater           | Unclassified        |
|  2 | Engineered      | Built environment    | Subway              |
|  3 | Environmental   | Aquatic              | Lake                |
|  4 | Environmental   | Terrestrial          | Unclassified        |
|  5 | Environmental   | Aquatic              | Oceanic             |
|  6 | Environmental   | Aquatic              | Unclassified        |
|  7 | Environmental   | Aquatic              | Groundwater         |
|  8 | Host-associated | Human                | Large intestine     |
|  9 | Host-associated | Mammals              | Large intestine     |
| 10 | Host-associated | Human                | Oral                |
| 11 | Host-associated | Human                | Unclassified        |
| 12 | Host-associated | Mammals              | Unclassified        |
| 13 | Host-associated | Plants               | Unclassified        |

### proposed mappings

Engineered / Wastewater / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Engineered / Built environment / Subway -> ???
note: add new classes 1) 'Subway' as subclass of 'transportation feature'; 2) 'environmental system determined by transportation feature'; 3) 'environmental system determined by subway'

Environmental / Aquatic / Lake -> ???
note: add new class 'lake environment' as subclass of 'aquatic environment'

Environmental / Terrestrial / Unclassified -> ???
note: need to decide how to handle 'Unclassified' values  

Environmental / Aquatic / Oceanic -> **envo:ENVO_01000321**; rdfs:label "sea water environment" **OR** **envo:ENVO_01000048**; rdfs:label "ocean biome"
note: Do we want to create a subclass of 'sea water environment' called 'ocean environment'? Also, is 'Oceanic' intended to reference an environmental system or a biome?

Environmental / Aquatic / Unclassified -> ???   
note: need to decide how to handle 'Unclassified' values  

Environmental / Aquatic / Groundwater -> ???  
note: add class 'groundwater environment' as subclass of 'aquatic environment'

Host-associated / Mammals / Large intestine -> ???  
note: add class 'mammalian large intestine environment' as subclass of 'mammalian digestive tract environment' 

Host-associated / Human / Large intestine -> ???  
note: add class 'human large intestine environment' as subclass of 'mammalian large intestine environment' (referenced above)

Host-associated / Human / Oral -> ???  
note: add class 'human oral environment' as subclass of 'human digestive tract environment'

Host-associated / Human / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Host-associated / Mammals / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Host-associated / Plants / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values

**Comment by wdduncan** [comment]
### SPECIFIC_ECOSYSTEM values (top 7 most occurring)

|    | ECOSYSTEM       | ECOSYSTEM_CATEGORY   | ECOSYSTEM_SUBTYPE   | SPECIFIC_ECOSYSTEM   |
|---:|:----------------|:---------------------|:--------------------|:---------------------|
|  0 | Engineered      | Built environment    | Unclassified        | Unclassified         |
|  1 | Engineered      | Wastewater           | Unclassified        | Unclassified         |
|  2 | Engineered      | Built environment    | Subway              | Unclassified         |
|  3 | Environmental   | Aquatic              | Lake                | Sediment             |
|  4 | Environmental   | Aquatic              | Lake                | Unclassified         |
|  5 | Environmental   | Terrestrial          | Unclassified        | Forest Soil          |
|  6 | Environmental   | Aquatic              | Oceanic             | Unclassified         |
|  7 | Environmental   | Aquatic              | Unclassified        | Unclassified         |
|  8 | Environmental   | Terrestrial          | Unclassified        | Unclassified         |
|  9 | Environmental   | Aquatic              | Oceanic             | Sediment             |
| 10 | Environmental   | Aquatic              | Groundwater         | Unclassified         |
| 11 | Environmental   | Terrestrial          | Unclassified        | Agricultural land    |
| 12 | Host-associated | Human                | Large intestine     | Fecal                |
| 13 | Host-associated | Mammals              | Large intestine     | Fecal                |
| 14 | Host-associated | Human                | Oral                | Unclassified         |
| 15 | Host-associated | Human                | Unclassified        | Unclassified         |
| 16 | Host-associated | Mammals              | Unclassified        | Unclassified         |
| 17 | Host-associated | Mammals              | Large intestine     | Unclassified         |
| 18 | Host-associated | Human                | Large intestine     | Unclassified         |
| 19 | Host-associated | Plants               | Unclassified        | Unclassified         |

### proposed mappings
#### Need to verify that data refers to an environment or the sample itself. For example, when I look at the descriptions for SPECIFIC_ECOSYSTEM == 'Fecal', I see descriptions like "Human feces microbial communities from a cholera patient". The physical specimen is the microbes ... right?

Engineered / Wastewater / Unclassified / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Engineered / Built environment / Subway / Unclassified ->  ???  
note: need to decide how to handle 'Unclassified' values  

Environmental / Aquatic / Lake / Sediment -> **envo:ENVO_01001048**; rdfs:label "sediment environment"@en  
note: Need to add classes that the sediment is from a lake. See above comment about "Environmental / Aquatic / Lake". Also, is there an assumption that lakes are freshwater?   

Environmental / Aquatic / Lake / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Environmental / Terrestrial / Unclassified / Forest Soil -> ???   
note: Add class "forest soil enviroment" as subclass of "soil enviroment". Also, this is interesting b/c the "ECOSYSTEM_SUBTYPE" value is "Unclassified". 

Environmental / Aquatic / Oceanic / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Environmental / Aquatic / Unclassified / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Environmental / Terrestrial / Unclassified / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Environmental / Aquatic / Oceanic / Sediment -> **envo:ENVO_01001050**; rdfs:label "saline sediment environment"@en     
note: add information that the sediment is from an ocean  

Environmental / Aquatic / Groundwater / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Environmental / Terrestrial / Unclassified / Agricultural land -> **envo:ENVO_01000311**; rdfs:label "cultivated environment"  note: Do we need to further specify that the cultivated environment is used for growing food? Also, the "ECOSYSTEM_SUBTYPE" value is "Unclassified". 

Host-associated / Mammals / Large intestine / Fecal -> ???   
note: add subclass 'mammalian fecal environment' as subclass of 'fecal environment'  

Host-associated / Human / Large intestine / Fecal ->   
note: add subclass 'human fecal environment' as subclass of 'mammalian fecal environment' (referenced above)  

Host-associated / Human / Oral / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Host-associated / Human / Unclassified / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Host-associated / Mammals / Unclassified / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Host-associated / Mammals / Large intestine / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Host-associated / Human / Large intestine / Unclassified -> ???  
note: need to decide how to handle 'Unclassified' values  

Host-associated / Plants / Unclassified / Unclassified ->???  
note: need to decide how to handle 'Unclassified' values

**Comment by wdduncan** [comment]
@cmungall I did an analysis looking for null values followed by a non-null values. I did not find any such rows. Details are found in the notebook: `gold-env-null-value-analysis.ipynb`

**Comment by cmungall** [comment]
This is v useful. We can compare this with kai's mappings. But for now let's switch focus to #6 and #7
