### ISSUE TITLE
duplicate GOLD path values

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#60]
In the most recent download of the GOLD path ids:  
https://gold.jgi.doe.gov/downloads

There is a row in which the GOLD values are duplicated.

4035 | Environmental | Aquatic | Marine | Neritic zone | Sediment |   
-- | -- | -- | -- | -- | -- | --
4048 | Environmental | Aquatic | Marine | Neritic zone | Sediment |

**Comment by TBKReddy** [comment]
Hi Bill,

Thanks for checking with us.

No these two paths are not referring to oil-contaminated sediment. One is specific for oil-contaminated sediment and the other is for anything oil-contatminated.

The following links on GOLD website showing what are the different samples using these paths. 

https://gold.jgi.doe.gov/biosamples?page=1&asc=Biosample.Specific+Ecosystem&Biosample.Ecosystem+Path+Id=%3D4011&count=25

https://gold.jgi.doe.gov/biosamples?page=1&asc=Biosample.Specific+Ecosystem&Biosample.Ecosystem+Path+Id=4007&count=25

Whenever you see some seemingly similar paths or something that you may have some doubt, please feel free to explore GOLD website to see samples using those paths.
That should help you in seeing these paths in the context of their use.
Hope this helps.

Let me know if you have any questions.

Cheers,

Reddy.

**Comment by wdduncan** [comment]
This ticket is referring to neritic zone sediment. I think you may have confused this with another email I sent about oil-contaminated sediment.

**Comment by wdduncan** [comment]
@TBKReddy 
Here are the oil-contaminated paths I think you are referring to:

4011 | Environmental | Aquatic | Marine | Oceanic | Oil-contaminated
-- | -- | -- | -- | -- | --
4007 | Environmental | Aquatic | Marine | Oceanic | Oil-contaminated sediment

As you can see, these are different than the ones I posted the issue about.

**Comment by jagadishcs** [comment]
The path Environmental::Aquatic::Marine::Neritic zone::Sediment is now assigned only to ID 4048.
