### ISSUE TITLE
Review GOLD to MIxS/ENVO triad

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#61]
The GOLD paths and some partial mappings have been uploaded to:

https://docs.google.com/spreadsheets/d/1Tfbj0QCckk_S6ldyVJZcTdJKZHd1D9Y4whWz2CjeIcI/edit#gid=1310900750

The mappings need to be reviewed. Reviewers should fill in their initials and date when completed. Please fill in the notes column if you disagree with a mapping or find other problems.

**Comment by kaiiam** [comment]
Looks good @wdduncan thanks for adding the provenance info.

**Comment by wdduncan** [comment]
I have added a column for just the FICUS studies based on the work done by @jagadishcs in issue #58

**Comment by wdduncan** [comment]
see #35
