### ISSUE TITLE
Gather Identify layer information

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#69]
Stan will gather information about vocabularies and layers to share with the team & upload to the Github site.
 - 17 layers, some are repetitive.
- This is instrument specific. This will be in the doc shared by Stan.
- Not all layers will have all resolutions.

Further tasks include:
- Determining wich MIxS fields can be mapped to.

**Comment by cmungall** [comment]
Closed in favor of #66
