### ISSUE TITLE
Create IDs for GOLD tree nodes

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-metadata#7]
Algorithm:

for any 5 tuple, with depth N (1 <= N <=5), i.e. t1,t2,...,tn
create a class:

 * uri: hash of t1,..,tn
 * rdfs:label "t1 t2 ... tn"
 * rdfs:subClassOf id of t1,..,t(n-1)

**Comment by wdduncan** [comment]
@cmungall 
Ontology based on data in `Biosample_all.tsv.gz` has been created in the `microbiomedata/GOLD-ontology-translation` repo.  

Path to ontology is `GOLD-ontology-translation/notebooks/output/gold-dataset-translation.owl`.

**Comment by cmungall** [comment]
@wdduncan can this ticket be closed?

I recall discussion:

> GOLD ecosystem path information is not consistent across tables. The five tuples used to describe the sample may differ even though they have the same path ids.

Is this the case? If so we should follow up with @jagadishcs and Reddy on the Monday meeting

**Comment by wdduncan** [comment]
As far as I know, this has not been done yet. Let's follow up on Monday morning.

**Comment by wdduncan** [comment]
We will track this using ticket #35
