### ISSUE TITLE
Create json template Bio Scales required fields using CEDAR

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#72]
Stan is going to give this a whirl ...

**Comment by dehays** [comment]
Requirements for NMDC data portal as described in 1.5 of the work plan will come out of further NMDC data portal design with input from BioScales.  Work distribution will be determined by scoping of work with CEDAR.  (This issue may be reopened, but at this point in time it is premature to do work here without specifics defined for the metadata submission portal.)
